### PR TITLE
Revert "Dear lord jesus let this work"

### PR DESCRIPTION
**Pull request by piperswe**
Reverts ID10T-Errors/ID10T-Errors.github.io#30

### CODE REVIEW

**Comment by ztaylor54** [comment]
That was kind of glorious, you have to admit.

**Comment by piperswe** [comment]
> That was **kind of** glorious

**Comment by ztaylor54** [comment]
I'm not seeing an issue with css? Go ahead and make a post on SE. I've lost Internet due to storms.

**Comment by piperswe** [comment]
http://stackoverflow.com/questions/34243813/markdown-not-rendering-properly-with-jekyll-although-i-suspect-css-is-the-culpr

**Pull request merged**
