### PR TITLE
Add new post announcing development of Signum Workshop

### PR DESCRIPTION
**Pull request by ztaylor54**

### CODE REVIEW

**Comment by piperswe** [comment]
Looks good to me, merging

**Comment by piperswe** [comment]
I'm an idiot.

**Comment by piperswe** [comment]
Something broke: http://www.ctftoolkit.com/2015/12/11/signum.html

**Comment by ztaylor54** [comment]
Why'd you revert it?

**Comment by piperswe** [comment]
I thought that something was something that it wasn't so I tried to fix it. Turns out there was nothing to fix. ¯_(ツ)_/¯

**Pull request merged**
